/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {


    public static void main(String[] args) {

        System.out.println("this is graphs");

        Graph graph=new Graph();

        graph.addVertex("A");
        graph.addVertex("B");
        graph.addVertex("C");

        graph.addEdges("A","B");
        graph.addEdges("B","C");
        graph.addEdges("A","C");

        System.out.println(graph.printGraph());

Vertex vertex=new Vertex("A");
        System.out.println(graph.get_nodes());
        System.out.println( graph.get_neighbors(vertex));

    }
}
