/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        linkedList<String> newlist = new linkedList();
        newlist.insert("any");
        newlist.insert("value");
        newlist.insert("we");
        newlist.insert("have");
        newlist.insert("it");
        newlist.insert("in ");
        newlist.insert("this");
        newlist.insert("link list");

        System.out.println(newlist.includes("any"));
//        Scanner scanner=new Scanner(System.in);
//        System.out.println("enter number you will add before the first node that has the value specified ");
//     String s=scanner.nextLine();
//        System.out.println("enter number you will add it ");
//        String s2=scanner.nextLine();
//        newlist.insertBefore(s,s2);
        System.out.println(newlist.toString1());
    }
}
