/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import hashtable.structor.HashMap;

public class App {


    public static void main(String[] args) {

        System.out.println("hallo this is hash table ");
        HashMap<String ,String> hashMap=new HashMap<>();
        hashMap.put("firstOne","ali");
        hashMap.put("secondOne","wesam");
        hashMap.put("ThirdOne","kahed");
        hashMap.put("lastOne","fared");
        System.out.println(hashMap.get("ThirdOne"));

        System.out.println(hashMap.keys());

        System.out.println(hashMap.contains("any"));

        String s = "Once upon a time, there was a ";
        String firstWord = hashMap.hashmap_repeated_word(s);
        if (!firstWord.equals("NoRepetition"))
            System.out.println("First repeated word :: " + firstWord);
        else
            System.out.println("No Repetitionn");
    }
}
