/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class Library {


    public static void main(String[] args) {
        System.out.println("hallo world" );
    }
}
