/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
@Test void testInsertionSort(){
    Library library=new Library();
    int [] arr={8,4,23,42,16,15};

    library.InsertionSort(arr);

   int[] result={4, 8, 15, 16, 23, 42};
assertArrayEquals(result,arr);

}
    @Test void testMergaSort(){
        Library library=new Library();
        int [] arr={8,4,23,42,16,15};

        library.MergeSort(arr);

        int[] result={4, 8, 15, 16, 23, 42};
        assertArrayEquals(result,arr);

    }
    @Test void testQuickSort(){
        Library library=new Library();
        int [] arr={8,4,23,42,16,15};
int end=arr.length-1;
        library.QuickSort(arr,0,end);

        int[] result={4, 8, 15, 16, 23, 42};
        assertArrayEquals(result,arr);

    }

}
