/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {

    }
    @Test void toString1Test(){
        linkedList<String> newlist = new linkedList();
     String result="{link list} ->{this} ->{in } ->{it} ->{have} ->{we} ->{value} ->{any} ->null";



    }
    @Test void includes(){
        linkedList<String> newlist = new linkedList();
        boolean a=newlist.includes("any");
        assertFalse(a);

    }
}
